export interface User {
    id?: number; // Optional because it will be generated by the backend
    name: string;
    email: string;
    password: string;
    role: 'ADMIN' | 'OD' | 'CD'; // Roles as a union type of string literals
  }